### ISSUE TITLE
Can not display transaction informations (Epay)

### ISSUE THREAD

**Issue by giano574** [bambora/checkout-magento-v2.x#9]
Testing the Epay payment gateway everything seems to work fine, except updating the order in Magento. The payment is created in Epay, but the order information in Magento says "Can not display transaction informations" and the order status is still "Pending"

DANISH:
Ved test af Epay betaling lader alt til at fungere rigtigt, med undtagelse af opdatering af ordre i Magento. Betalingen oprettes i Epay, men under ordren i Magento står fejlen "Can not display transaction informations" og status på ordren er stadig "Pending".

**Comment by giano574** [comment]
There are no errors in bambora.log

DANISH:
Der kommer i øvrigt ingen fejl i bambora.log

**Comment by giano574** [comment]
It was a server error on our side

DANISH:
Det var en fejl i vores serveropsætningen

**Comment by giano574** [comment]
Everything works now, but the message "Can not display transaction informations -" still appears.

DANISH:
Alt virker som det skal nu, men meddelelsen "Can not display transaction informations -" dukker stadig op.
![screenshot_8](https://cloud.githubusercontent.com/assets/17013720/23359000/818653ee-fce4-11e6-86c5-8d1e966c49cb.png)

**Comment by AllanWLie** [comment]
Hi @giano574 

We have found an error in the module, causing you not to get the "reason" message for not being able to display the transaction informations.

The error will be fixed in the next release. In the meanwhile you can change this line in the code in the module in your local installation:
https://github.com/bambora/bambora-online-magento-v2.x/blob/master/Helper/Data.php#L430

On the code line you will have to change this $response->epayresponse to $response->epayResponse  (the difference is Response need to be with capital R) the error occurs twice in the code line.

Alterneativli you can look in the ePay adminstration for why you are not able to look up transaction informations. 

or you can contact our support at support@bambora.com and tell them about your problem. Remember to write your merchant number also the transaction id.

Kind regards
Allan

**Comment by giano574** [comment]
Great, thanks

**Comment by AllanWLie** [comment]
@giano574 
We have now released a new version where your issue is fixed.
Link to new version https://github.com/bambora/bambora-online-magento-v2.x/releases/latest
